jobs:
  build:
    if: startsWith(github.event.head_commit.message, '[maven-release-plugin]') !=
      true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - cache: maven
      continue-on-error: true
      distribution: microsoft
      java-version: 11
      name: Set up JDK 11
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B verify --file pom.xml
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Git-release
      run: './mvnw -B -pl :gctoolkit -Pjreleaser jreleaser:release

        '
name: GCToolKit Pre-release Notes
on:
  repository_dispatch:
    types: trigger-ga___early_access.yml
