jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: microsoft
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B verify -Dmaven.compiler.release=${{ matrix.java }} --file pom.xml
    strategy:
      matrix:
        java:
        - 11
        - 17
        - 21
name: GCToolKit build with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
