jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout project
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        fetch-depth: 0
        ref: main
    - continue-on-error: true
      name: Cache Maven
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Setup Java JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: microsoft
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.GPG_PRIVATEKEY }}
        java-version: '11'
        server-id: ossrh
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Configure Git user
      run: 'git config user.email "actions@github.com"

        git config user.name "GitHub Actions"

        '
    - continue-on-error: true
      id: version
      name: Version
      run: 'release_version=$(./mvnw help:evaluate -Dexpression=project.version -q
        -DforceStdout)

        release_version=${release_version%-*}

        echo ::set-output name=version::${release_version}

        '
    - continue-on-error: true
      env:
        MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        MAVEN_USERNAME: ${{ secrets.SONATYPE_NAME }}
      name: Release
      run: "export GPG_TTY=$(tty)\n./mvnw -Darguments=\"-Drelease=true\" -B release:prepare\
        \ release:perform -Drelease=true \\\n  -Drepository.url=https://${{ github.actor\
        \ }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git\n"
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Git-release
      run: './mvnw -B versions:set -DnewVersion=${{steps.version.outputs.version}}

        ./mvnw -B -pl :gctoolkit -Pjreleaser jreleaser:release

        '
name: Publish to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
